[package]
name = "website_crawler"
version = "0.6.0"
authors = ["Jeff Mendez <jeff@a11ywatch.com>"]
edition = "2018"
description = "tokio based web crawler with gRPC streams that runs fast"
license = "MIT"
readme = "README.md"
repository = "https://github.com/A11yWatch/crawler"
keywords = ["crawler", "web-crawler", "spider", "web-indexer", "site-map-generator"]
categories = ["accessibility", "asynchronous"]

[dependencies]
tokio = { version = "^1.20.1", features = [ "rt-multi-thread", "net", "macros", "sync", "time" ] }
tonic = { version = "0.8.0" }
prost = "0.11.0"
prost-types = "0.11.0"
reqwest = { version = "0.11.11", features = ["cookies", "brotli", "native-tls-alpn"] }
scraper = "0.13"
url = "2.2.2"
regex = { version = "^1.5.0", optional = true }
hashbrown = { version = "0.12.3" }
log = "0.4.16"
lazy_static = "1.4.0"
ua_generator = "0.3.0"
percent-encoding = "2.1.0"
env_logger = "0.9.0"

[[bin]]
name = "health_client"
path = "src/hc_client.rs"

[build-dependencies]
tonic-build = { version = "0.8.0" }
quote = "1.0.18"
failure_derive = "0.1.8"
cc = "=1.0"
rustc_version = "0.4.0"

[dev-dependencies]
once_cell = "1.2.0"
