[package]
name = "website_crawler"
version = "0.4.6"
authors = ["Jeff Mendez <jeff@a11ywatch.com>"]
edition = "2018"
description = "gRPC web crawler that's very fast"
license = "MIT"
readme = "README.md"
repository = "https://github.com/A11yWatch/crawler"
keywords = ["crawler", "web-crawler", "spider", "web-indexer", "site-map-generator"]
categories = ["accessibility", "asynchronous"]

[dependencies]
tokio = { version = "^1.17.0", features = [ "rt-multi-thread", "net", "macros", "sync", "time" ] }
tonic = "0.7"
prost = "0.10"
num_cpus = "1.13.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
scraper = "0.13"
robotparser-fork = "0.10.5"
url = "2.2.2"
rayon = "1.5.2"
regex = { version = "^1.5.0", optional = true }
hashbrown = { version = "0.12" }
log = "0.4.16"
lazy_static = "1.4.0"
ua_generator = "0.2.2"

[[bin]]
name = "health_client"
path = "src/hc_client.rs"

[build-dependencies]
tonic-build = "0.7"
quote = "1.0.18"
failure_derive = "0.1.8"
cc = "=1.0"
rustc_version = "0.4.0"

[dev-dependencies]
once_cell = "1.2.0"
