[package]
name = "website_crawler"
version = "0.2.1"
authors = ["jeffreymendez <jeffmendez19@gmail.com>"]
edition = "2021"
description = "crawl all urls on a website async & sync"
license = "MIT"
readme = "README.md"
repository = "https://github.com/A11yWatch/crawler"
keywords = ["crawler", "website-crawler", "spider", "url-finder", "site-map-generator"]
categories = ["web", "accessibility", "crawler"]

[dependencies]
spider = "1.5.1"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "net", "macros"] }
tonic = "0.7"
prost = "0.10"
num_cpus = "1.13.0"

[[bin]]
name = "health_client"
path = "src/hc_client.rs"

[build-dependencies]
tonic-build = "0.7"

[profile.release]
codegen-units = 1
lto = true

[dev-dependencies]
once_cell = "1.2.0"