[package]
name = "website_crawler"
version = "0.6.25"
authors = ["Jeff Mendez <jeff@a11ywatch.com>"]
edition = "2018"
description = "gRPC tokio based web crawler"
license = "MIT"
readme = "README.md"
repository = "https://github.com/a11ywatch/crawler"
keywords = ["crawler", "web-crawler", "spider", "web-indexer", "site-map-generator"]
categories = ["accessibility", "asynchronous"]

[dependencies]
tokio = { version = "^1.21.0", features = [ "rt-multi-thread", "net", "macros", "sync", "time" ] }
tokio-stream = "0.1.9"
tonic = { version = "0.8.0" }
prost = "0.11.0"
prost-types = "0.11.0"
reqwest = { version = "0.11.11", features = ["brotli", "native-tls-alpn"] }
scraper = "0.13"
url = "2.2.2"
regex = { version = "^1.5.0", optional = true }
hashbrown = { version = "0.12.3", features = [ "rayon" ] }
log = "0.4.16"
lazy_static = "1.4.0"
ua_generator = "0.3.0"
percent-encoding = "2.1.0"
env_logger = "0.9.0"
rayon = "1.5.3"
string_concat = "0.0.1"

[target.'cfg(all(not(target_os = "android"), not(target_os = "freebsd")))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-sys = { version = "0.5.0", optional = true }

[[bin]]
name = "health_client"
path = "src/hc_client.rs"

[build-dependencies]
tonic-build = { version = "0.8.0" }
quote = "1.0.18"
failure_derive = "0.1.8"
cc = "^1.0.13"
rustc_version = "0.4.0"
fs_extra = "^1.1"

[dev-dependencies]
once_cell = "1.2.0"

[profile.release]
codegen-units = 1
lto = "fat"

[features]
jemalloc = ["jemallocator", "jemalloc-sys"]
