FROM rustlang/rust:nightly

ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8000

ARG CRAWL_URL
ARG CRAWL_URL_COMPLETE
ENV CRAWL_URL="${CRAWL_URL:-http://api:8080/api/website-crawl}"
ENV CRAWL_URL_COMPLETE="${CRAWL_URL_COMPLETE:-http://api:8080/api/website-crawl-background-complete}"

WORKDIR /usr/src/app

# TODO: remove .dotenv usage for system
RUN echo "CRAWL_URL=$CRAWL_URL" >> .env

COPY . .

CMD [ "cargo", "run"]
