version: 2.1
jobs:
  crawler:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: large
    environment:
      RUSTFLAGS: "-D warnings"
      IMAGE_NAME: a11ywatch/crawler
      DOCKER_BUILDKIT: 0
      BUILDX_PLATFORMS: linux/amd64,linux/arm64

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run:
          name: Login to Dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Install buildx
          command: |
            curl --output docker-buildx --silent --show-error --location --fail --retry 3 \
            "https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
            chmod +x rustup.sh
            ./rustup.sh -y
            source "$HOME"/.cargo/env
            sudo apt-get update
            sudo apt-get -y --no-install-recommends install libssl-dev qemu gcc-aarch64-linux-gnu qemu-user-static

      - run: 
          name: Test image
          command: cargo test --all-features

      - run:
          name: Setup buildx
          command: docker buildx create --driver docker-container --name local --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use

      - run: 
          name: Build and Push Latest (Alpine)
          no_output_timeout: 1h
          command: docker buildx build  --ulimit nofile=1024000:1024000 --platform $BUILDX_PLATFORMS -t $IMAGE_NAME:latest -t $IMAGE_NAME:alpine --push . -f docker/Dockerfile

      - save_cache:
          paths:
            - ~/usr/local/lib/target
          key: node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}

workflows:
  build_and_test:
    jobs:
      - crawler