version: 2.1
jobs:
  crawler:
    docker:
      - image: a11ywatch/crawler
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cargo test
      - save_cache:
          paths:
            - ~/usr/local/lib/target
          key: node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
workflows:
  build_and_test:
    jobs:
      - crawler
