version: 2.1
jobs:
  crawler:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    environment:
      RUSTFLAGS: "-D warnings"
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
            chmod +x rustup.sh
            ./rustup.sh -y
            source "$HOME"/.cargo/env
      - run: cargo test --all-features
      - save_cache:
          paths:
            - ~/usr/local/lib/target
          key: node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
workflows:
  build_and_test:
    jobs:
      - crawler
