version: 2.1
jobs:
  crawler:
    docker:
      - image: rustlang/rust:nightly
    resource_class: large
    environment:
      RUSTFLAGS: "-D warnings"
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: apt-get update && apt-get install -y --no-install-recommends  gcc cmake libc6 libssl-dev
      - run:
          command: cargo install --no-default-features --path . && cargo test
          no_output_timeout: 30m
      - save_cache:
          paths:
            - ~/usr/local/lib/target
          key: node-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
workflows:
  build_and_test:
    jobs:
      - crawler
